### ISSUE TITLE
Is this in any form working?

### ISSUE THREAD

**Issue by ManuLinares** [nicman23/emgd_ddx#1]
Hi, how can I use the "emgd_drv.so" produced by the compilation?
I copied the file to "/usr/lib/xorg/modules/drivers/" but have no idea how to proceed.

I'm still using the "gma500_gfx" kernel module, using "archlinux32"

**Comment by nicman23** [comment]
lol i have forgotten i even had touched gma500

sorry got no idea, i should probably archive the repo
